export const SCREENS = {
    HOME: 'HOME',
    SEARCH: 'SEARCH',
    LIST: 'LIST',
    PROFILE: 'PROFILE',
    MOVIE_DETAIL: 'MOVIE_DETAIL',
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    REGISTER: 'REGISTER',
};
