export const SCREENS = {
  HOME: "HOME",
  SEARCH: "SEARCH",
  LIST: "LIST",
  PROFILE: "PROFILE",
  MOVIE_DETAIL: "MOVIE_DETAIL",
  MOVIES_BY_GENRE: "MOVIES_BY_GENRE",
  SIGN_IN: "SIGN_IN",
  SIGN_UP: "SIGN_UP",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",
};
